-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE 'REMINDER_ACKNOWLEDGED';
ALTER TYPE "ActivityType" ADD VALUE 'CALIBRATION_REMINDER_ACKNOWLEDGED';
ALTER TYPE "ActivityType" ADD VALUE 'RENTAL_REMINDER_ACKNOWLEDGED';
ALTER TYPE "ActivityType" ADD VALUE 'MAINTENANCE_REMINDER_ACKNOWLEDGED';
ALTER TYPE "ActivityType" ADD VALUE 'SCHEDULE_REMINDER_ACKNOWLEDGED'; 